mkdir -p build
cd build
# A30 CMAKE_CUDA_ARCHITECTURES=80
# A40 CMAKE_CUDA_ARCHITECTURES=86
# A100 CMAKE_CUDA_ARCHITECTURES=80
cmake -D CMAKE_BUILD_TYPE=Release -D WITH_GPU=ON -D CMAKE_CUDA_ARCHITECTURES=80 ..
make -j 16

